### ISSUE TITLE
Can we have an option to remove the gap between pictures?

### ISSUE THREAD

**Issue by jackblk** [fuzetsu/manga-loader#25]
If we have this option, reading webtoon would be nicer :D.

Thank you :D.

**Comment by fuzetsu** [comment]
You can do this in the current version using custom css.
In the settings paste this into a new profile (called nogaps or webtoon or something).
```
.ml-counter { display: none; }
.ml-images img { margin: 0 auto; }
```
I might add some default profiles with common stuff like this at some point, but this should suffice for now.
