### ISSUE TITLE
Infinite loop on Image.onerror cause high CPU usage

### ISSUE THREAD

**Issue by sudoerChris** [fuzetsu/manga-loader#52]
an error in the svg code of IMAGES.refresh_large causes image.onerror called infinitely, remove  fill="#fff" in the svg to fix it

**Comment by AlexAMCS** [comment]
> 
> 
> an error in the svg code of IMAGES.refresh_large causes image.onerror called infinitely, remove fill="#fff" in the svg to fix it

Thanks for this, fixed the issue for me.
