### ISSUE TITLE
maybe a dumb question: is there a guide on how to setup a custom css for simple things? like max height?

### ISSUE THREAD

**Issue by xerance** [fuzetsu/manga-loader#58]
topic;

I just kinda want to limit the height of an image so it always fits my screen. is there a a guide or something for this?

edit: copied fuzetsu script for base idea

all i needed:

.ml-images img {
  max-height: 1000px;
}

**Comment by fuzetsu** [comment]
Yep, you got it!

you might also like

```css
.ml-images img {
  max-height: 100vh;
}
```

That'll make sure it always fits the window height, so it'll work even if you used a smaller window 👍
