### ISSUE TITLE
kissmanga not working from today 

### ISSUE THREAD

**Issue by RootAndroid58** [fuzetsu/manga-loader#60]
they may have updated something i see the button on bottom but when i click load manga it dont do anything 
`read property 'length' of undefined in console log of google chrome`

```
  numpages: function() {
    return W.lstImages.length;       <-- length is undefined here line no 520 
  },
```
Tried reinstalling the script

**Comment by fuzetsu** [comment]
Should be fixed now thanks to #61

**Comment by tv1mdb** [comment]
Kissmanga is no longer working on my end as well, changing the code like this greasypost comment fixed it for me: https://greasyfork.org/it/forum/discussion/comment/97549/#Comment_97549
@fuzetsu

**Comment by fuzetsu** [comment]
Ah, looks like it wasn't fully broken before but it just uses different variables based on the view mode.
Shipped a quick fix that handles both hopefully.. :+1: 

https://github.com/fuzetsu/manga-loader/commit/25e73373c957a547cdf630bc02f26a7e069560a6

**Comment by tv1mdb** [comment]
Works like a charm on both variables, **👍**
